version: "3"

services:

    guacamole-ts:
      image: tailscale/tailscale:latest
      container_name: guacamole-ts
      hostname: guacamole
      environment:
        - TS_AUTHKEY=${OAUTH_KEY}?ephemeral=true #Requires a .dev file with the variable OAUTH_KEY defined
        - TS_EXTRA_ARGS=--advertise-tags=tag:container
        - TS_STATE_DIR=/var/lib/tailscale
        - TS_USERSPACE=false
        - TS_SERVE_CONFIG=/config/serve-config.json
      volumes:
        - ${PWD}/guacamole-ts/state:/var/lib/tailscale
        - ${PWD}/config:/config
      devices:
        - /dev/net/tun:/dev/net/tun
      cap_add:
        - net_admin
      networks:
        guac-net:
      restart: unless-stopped

    guacd:
      container_name: guacd
      image: guacamole/guacd
      restart: unless-stopped
      networks:
        guac-net:
          ipv4_address: 172.20.0.2
    
    guacweb:
      container_name: guac_web
      image: guacamole/guacamole
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: guacamole_db
        MYSQL_HOSTNAME: 172.20.0.3
        MYSQL_PASSWORD: pass123
        MYSQL_USER: guacamole_user
        GUACD_HOSTNAME: 172.20.0.2
      depends_on:
        - guacamole-ts
        - guacamole-sql
        - guacd
      network_mode: service:guacamole-ts
      
    
    guacamole-sql:
      container_name: guac-sql
      image: mysql
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: Password123!
      volumes:
        - dbdata:/var/lib/mysql
      networks:
        guac-net:
          ipv4_address: 172.20.0.3

volumes:
  dbdata:

networks:
  guac-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"