version: "3"

services:
    guacd:
      container_name: guacd
      image: guacamole/guacd
      restart: unless-stopped
      networks:
        guac-net:
          ipv4_address: 172.20.0.2
    
    guacweb:
      container_name: guac_web
      image: guacamole/guacamole
      ports:
        - 8080:8080
      secrets:
        - mysql_user_pass
      environment:
        MYSQL_DATABASE: guacamole_db
        MYSQL_HOSTNAME: 172.20.0.3
        MYSQL_PASSWORD: /run/secrets/mysql_user_pass
        MYSQL_USER: guacamole_user
        GUACD_HOSTNAME: 172.20.0.2
      depends_on:
        - guacamole-sql
        - guacd
      networks:
        guac-net:
      restart: unless-stopped

    guacamole-sql:
      container_name: guac-sql
      image: mysql
      secrets:
        - mysql_root_pass
      environment:
        MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_pass
      volumes:
        - dbdata:/var/lib/mysql
      networks:
        guac-net:
          ipv4_address: 172.20.0.3
      restart: unless-stopped

volumes:
  dbdata:

secrets:
  mysql_user_pass:
    file: ./secrets/mysql_user_pass
  mysql_root_pass:
    file: ./secrets/mysql_root_pass

networks:
  guac-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"